name: Migrate testing database 

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set testing properties
        run: echo setting properties
      - name: Migrating database
        run: sh run.sh
